### ISSUE TITLE
[Documentation] Update basis audit

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#24]
Audit: #17 

Implement the structure as discussed in the audit. 

- [x] Structural updates - @karntrehan 
- [x] Addition of user and cycle management docs - @karntrehan 
- [x] Macro architecture - @karntrehan 
- [x] Assessment Generation Agent - @nikhil241 
- [x] ASR API - @sukh-ai 
- [ ] Data service and core service docs to be updated - @dhruv-1001 
- [ ] Add BSTT Player documentation - @dhruv-1001 
- [ ] Add installation steps - @dhruv-1001 
- [x] web-orchestrator and web-orchestrator_installation to be updated - @amit-s19 
- [x] android-orchestrator and android-orchestrator_installation to be added - @charanpreet-s 
- [ ] Automation elements to be added - @AakashSatpute119

**Comment by karntrehan** [comment]
WIP: https://github.com/BharatSahAIyak/docs/tree/feature/nisai-0.3.0-cleanup

**Comment by karntrehan** [comment]
@sukh-ai > To be added here: https://github.com/BharatSahAIyak/docs/blob/feature/nisai-0.3.0-cleanup/docs/nipun_sahaiyak/components/be/asr-service.md
# ASR 

## Need

## Flow

### Version
- Model used
- Accuracy
- Fuzzy logic used

## APIs
### ASR
### Verify

## Benchmarking suite

## Roadmap

**Comment by sukh-ai** [comment]
@karntrehan I have raise the [PR](https://github.com/BharatSahAIyak/docs/pull/76) it is still in progress, few sections are remaining like benchmarking suite and roadmap details

**Comment by sukh-ai** [comment]
@karntrehan Added the benchmarking and roadmap details
