### ISSUE TITLE
BE Tech Debts, Features & Enhancements Master Tracker

### ISSUE THREAD

**Issue by karntrehan** [NipunSahAIyak/.github#9]
I am creating this tracker to keep track of things I need to add for a better developer experience with NisAi. They are not listed in the order of priority and priority needs to be discussed. 

- [x] Change `participant_id` to `assessee_id`. 
- [x] Make level to `int`
- [x] Remove `is_passed`.
- [x] Re-discuss assessment table design. 
- [ ] Write validators for every attribute that is using a JSONB postgres column (data-service assessments etc.) 
- [ ] Add unit tests for Integration, Core-Service, and Generation Service.  
- [x] Increase e2e test coverage for modules. 
- [x] Setup code-cov or equivalent. 
- [x] Cleanup ingestor service to use Abstract classes for different players. 
- [ ] Write a player-specific config validator.
- [ ] Setup pre-commit for repo. 
- [ ] Docs for ODK player onboarding [Not high priority] 
- [ ] Implement automatic grouping of forms for ODK central player. 
- [ ] Discussion on Passage Questionnaire ACP. Currently, we have 1 question in 1 questionnaire - with the time, the competency mapping list will increase a lot over time.

**Comment by karntrehan** [comment]
Deprioritised.
